version: 3.1

services:
  ###
  # Workspace -> This is where you develop in
  ###
  workspace:
    image: "cloudmyit/php-cicd:php-${VERSION_WORKSPACE_PHP}"
    volumes:
      - ${CODE_PATH}:/opt
  
  ###
  # Serve a website if needed
  ###
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ${CODE_PATH}/.devcontainer/nginx/:/etc/nginx/conf.d
      - ${CODE_PATH}:/opt
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  # PHP-FPM so NGINX can host PHP
  php-fpm:
    image: "cloudmyit/php-cicd:php-${VERSION_PHP}"
    ports:
      - "9000:9000"
    volumes:
      - ${CODE_PATH}:/opt

  ###
  # Databases
  #
  # Each database has a "database" and "database-dev" server
  # The "database" server should be used with nginx
  #   Its data is stored in the codepath
  # The "database-dev" server should be used when running tests
  ###

  # MySQL
  mysql:
    image: "cloudmyit/php-cicd:mysql-${VERSION_MYSQL}"
    volumes:
      - ${CODE_PATH}/.devcontainer/mysql:/var/lib/mysql
  mysql-dev:
    image: "cloudmyit/php-cicd:mysql-${VERSION_MYSQL}"

  # PostgreSQL
  postgresql:
    image: "cloudmyit/php-cicd:postgresql-${VERSION_POSTGRESQL}"
    volumes:
      - ${CODE_PATH}/.devcontainer/postgresql:/var/lib/postgresql/data
  postgresql-dev:
    image: "cloudmyit/php-cicd:postgresql-${VERSION_POSTGRESQL}"